### PR TITLE
Fix reference storage and data model

### PR DESCRIPTION
**Pull request by ashkan-saeedi-mazdeh**
The provider could not store most key types because the reference contained invalid characters like . and +. Now I fixed it and it works

Also the provider was storing everything in one collection which wasn't intuitive at all and now it stores in collections based on type name.

### CODE REVIEW

**Comment by richorama** [comment]
Hey @ashkan-saeedi-mazdeh thanks for the PR.

I was looking at the rules around naming collection, documents etc.. on the arango website: 

https://docs.arangodb.com/2.8/NamingConventions/DocumentKeys.html

https://docs.arangodb.com/2.8/NamingConventions/CollectionNames.html

I think the ideal solution would be a a regex which replaced any invalid character with an underscore for documents.

For collections we should probably throw an error, as this is a human-provided setting rather than being auto generated.

According to the docs, a `+` in document id is permitted, were you having a problem?

I also noticed you changed the way the serialization worked. I preferred the orginal approach as the properties in the grain state became the properties in the arango document. The proposed approach is to turn the state into a single text string, which means you can't query it from arango. Was there a problem with the previous approach?

**Comment by richorama** [comment]
oh sorry, my bad, I hadn't realised that the collection names were auto generated

**Comment by ashkan-saeedi-mazdeh** [comment]
@richorama  Thanks for the review
1- The serialization to string was because I wasn't using LINQ queries so I will return it to object but In general do you think using SerializeObject and DeserializeObject  decrease querying capabilities, If yes why? Because of Orleans JSONSettings and inclusion of type names ?

I removed = and + because my keys were being saved but could not be found, the docs I read were old I guess or the StackOverflow thread wias wrong, I thought a-z,A-Z,0-9 and - _ are allowed only. 
Maybe I should investigate more, I highly doubt that length of the keys were the issue but I replaced GrainReference= with GR- so length might had an effect on it as well.

Also for collection names since 64 bytes is the limit, maybe I should omit the namespace?

For Replace/Regex, Do you think a compiled regex is faster? Shouldn't we only fix the issues which the Orleans key format makes and document that grain keys (in case of string keys) should follow these guidelines? I don't want to make it slow to serialize and deserialize without really needing to do so

**Comment by richorama** [comment]
I think the way to resolve the problem is to handle the grain keys correctly with the current mechanism of serializing. 

The grain key can be 254 characters, so we should be ok.

It might be an idea to offer key hashing option as a way to ensure the keys are valid, I'll add that some time in the future - not using SHA1 :¬P

I think regex is the fastest way to replace multiple invalid characters. They are compiled. I don't thin the processing cost is that high.

**Comment by ashkan-saeedi-mazdeh** [comment]
As my findings are @richorama  the + and = both made problems even with GR instead of GrainReference so it is a client bug I assume since the error is document not found, first right is successful, next writes with eTag and reads are all problematic with 404 exception 

Also I prefer to not check much and benchmark the regex against my current approach before coming to conclusions. Fill free to reject the PR, I will get the time to investigate at weekend

**Comment by richorama** [comment]
@ashkan-saeedi-mazdeh thanks for this PR. I have cherry picked the character replacement functionality and merged it into master. I'm going to look at the collection piece as well. Thank you!

**Comment by ashkan-saeedi-mazdeh** [comment]
@richorama  Thanks

If you look at my fork, I returned to your serialization way since my JSONs were being stored as just strings as you pointed and I store collections as their type name without any previous namespace part

I get last index of "." (dot) and substring from there.

I'm glad I could help a bit

I would like to write stats, reminders and membership tables over time too but we should agree on a single one or I should contribute another project to the repo. I'm using mine in prod from tomorrow so it is hard for me to use any other format.

What do you think we should do?

And the fork

https://github.com/ashkan-saeedi-mazdeh/Orleans.StorageProvider.Arango

**Comment by richorama** [comment]
Yep, I think the other providers could all live in the same repo, makes it easier for people to consume.

**Comment by richorama** [comment]
The `+` character problem has been fixed in the upstream repo.

https://github.com/ra0o0f/arangoclient.net/commit/6b36cb5fbf3f6c59f2c34af56100e5b036ed6605

awaiting nuget publish...

**Comment by AshkanSaeedi** [comment]
@richorama  Nice
I found out that the maintainer is Iranian, Will try to contact him to thank him and meet if possible. Godd news is that I can fix issues there if any faster

**Comment by richorama** [comment]
@AshkanSaeedi you've just switched avatar!

**Comment by ashkan-saeedi-mazdeh** [comment]
@richorama  no no! hell not, I was commenting by the account which is for a contract that I do and is using private repos on GH.

**Pull request closed without merging**
